'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''pnlOwnerForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOwnerForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtOName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvONAme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvONAme As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtOPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOPhone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revOPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revOPhone As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvOPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtOEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rewOEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rewOEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvOEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtONotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtONotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnOSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnOClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlPetForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPetForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtPName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvPName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtPBreed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPBreed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvPBreed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPBreed As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlPLocationLetter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPLocationLetter As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPLocationNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPLocationNum As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvPAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPAge As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlPOwner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPOwner As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PetStayData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PetStayData As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtPNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPNotes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cldPEntery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cldPEntery As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''cldPExit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cldPExit As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''btnPSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPClear As Global.System.Web.UI.WebControls.Button
End Class
